### ISSUE TITLE
Certificate validation does not work with openshift.patch-command

### ISSUE THREAD

**Issue by severi** [openshift/jenkins-client-plugin#106]
It seems that the openshift.patch command does not currently work when running it against another cluster. I have provided the Server Certificate Authority in the cluster configuration and I have been able to run for example openshift.create against that cluster. However when running the openshift.patch command I get the following error:

err=Unable to connect to the server: x509: certificate signed by unknown authority,

**Comment by gabemontero** [comment]
there are some slight differences in how the oc command line is constructed for `oc patch` vs. `oc create`, but on the surface, I don't see how they would impact setting of the cert param for `oc`

but we've also made some recent fixes wrt arg ordering that might have some impact on if / how the cert param is supplied (@coreydaley - do you recall if any use of `oc patch` was part of our testing for those)

@severi - the precise oc command line should be printed out prior to the error you noted ... could supply those for both your `oc patch` and `oc create`

could you also supply the exact version of this plugin that you are using?

thanks

**Comment by coreydaley** [comment]
I don't think that I tested it against another cluster.  I think we'll have a better idea of what is going on once we see the command line that is produced.  It is a newer command that was added so it might not have had much use yet, and reording of the args could def have either caused issues, or fixed the issue if this is an older version of the plugin.

**Comment by gabemontero** [comment]
On Wed, Jan 3, 2018 at 7:44 PM Corey Daley <notifications@github.com> wrote:

> I don't think that I tested it against another cluster. I think we'll have
> a better idea of what is going on once we see the command line that is
> produced. It is a newer command that was added so it might not have had
> much use yet, and reording of the args could def have either caused issues,
> or fixed the issue if this is an older version of the plugin.
>
gotcha sounds good thanks

**Comment by severi** [comment]
Here's the complete error log:

```
ERROR: patch returned an error;
{reference={}, err=Unable to connect to the server: x509: certificate signed by unknown authority, verb=patch, cmd=oc --server=https://clusteraddress.com --namespace=projectName --token=XXXXX patch deploymentconfig/jenkinslibs-sample-project-prod -p 'spec:
  template:
    spec:
      containers:
        - name: jenkinslibs-sample-project
          env:
            - name: JAVA_APP_DIR
              value: /app/jar
            - name: EXAMPLE
              value: default
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi' , out=, status=1}

Finished: FAILURE
```

OpenShift Client Jenkins Plugin 1.0.3
OpenShift Pipeline Jenkins Plugin 1.0.53

the create-command does not currently show any logs as it didn't fail (if I have the time I can take a look how to get logs from the successful commands later)

**Comment by coreydaley** [comment]
You should be able to place openshift.verbose() at the beginning of your pipeline and it will show the commands for the successful ones as well

**Comment by severi** [comment]
So it seems the commands are using a different value for --certificate-authority

I also validated that by disabling TLS Verify and removing the Server Certificate Authority from the settings the same error persists, create is successful but patch isn't



create
```
Verbose sub-step output:
	Command> oc --server=https://cluster.com --namespace=project --certificate-authority=/tmp/serverca2389423432112.crt --loglevel=8 --token=XXXXX create -f /tmp/create09345094502934234.markup -o=name 
	Status> 0
	StdOut>route/jenkinslibs-sample-project-prod
```

patch
```
Verbose sub-step output:
	Command> oc --server=https://cluster.com --namespace=project --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --loglevel=8 --token=XXXXX patch deploymentconfig/jenkinslibs-sample-project-prod -p 'spec:
  template:
    spec:
      containers:
        - name: jenkinslibs-sample-project
          env:
            - name: JAVA_APP_DIR
              value: /app/jar
            - name: EXAMPLE
              value: default
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi' 
	Status> 255
	StdOut>
```

**Comment by coreydaley** [comment]
Can you supply redacted versions of the create and patch commands that you are using?
Are you using openshift.patch or <selector>.patch?

**Comment by severi** [comment]
def response = openshift.patch("dc/foobar", "\'${fileContents}\'")
openshift.create(readFile("path/to/file"))

**Comment by coreydaley** [comment]
Also, are you using openshift.patch inside of an openshift.withCluster ?  What about create?

**Comment by severi** [comment]
both are inside of openshift.withCluster(clustername) and openshift.withProject(projectname)

**Comment by coreydaley** [comment]
could you supply the openshift.verbose output of the results when you used skipTLSVerify for the create and patch commands?

**Comment by coreydaley** [comment]
Are the openshift.create and openshift.patch inside of the SAME openshift.withCluster?

**Comment by gabemontero** [comment]
Yeah the patch is grabbing the default SA cert for some reason.  It would be *really* odd if that occurred within the same `withCluster` call, but you guys seem to be zeroing in on it - thanks

**Comment by severi** [comment]
yeah it is not within the same withCluster call but two different ones. 

When TLS verification is disabled -> 

Create:
```
Verbose sub-step output:
  Command> oc --server=https://cluster.com --namespace=project --loglevel=8 --token=XXXXX create -f /tmp/create123456721233.markup -o=name --insecure-skip-tls-verify 
  Status> 0
  StdOut>route/jenkinslibs-sample-project-prod
```


patch
```
Verbose sub-step output:
  Command> oc --server=https://cluster.com --namespace=project --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --loglevel=8 --token=XXXXX patch deploymentconfig/jenkinslibs-sample-project-prod -p 'spec:
  template:
    spec:
      containers:
        - name: jenkinslibs-sample-project
          env:
            - name: JAVA_APP_DIR
              value: /app/jar
            - name: EXAMPLE
              value: default
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi' 
  Status> 255
  StdOut>
```
