### ISSUE TITLE
DSL create ignores openshift.project and fails on trying to create in namespace=null

### ISSUE THREAD

**Issue by diamark** [openshift/jenkins-client-plugin#133]
error on openshift client plugin version=1.0.8, works with version=1.0.7

Might be related to https://github.com/openshift/jenkins-client-plugin/issues/96

Openshift (commercial): v3.6.173.0.21
oc: v3.7.1+ab0f056
kubernetes: v1.7.6+a08f5eeb62 
Jenkins: 2.107.1
openshift sync: 1.0.3 (rolled back from 1.0.9)
openshift client: 1.0.7 (rolled back from 1.0.8)

I have an openshift.create() call with a nested process in my pipeline:

`openshift.create(openshift.process(readFile("${tpldir}/${tpl}.yml"), this.setTplParams(args) ))`

The inner .process honors the namespace set via .withCluster(){.withProject($project)}. However, the outer .create issues a oc call with --namespace=null and fails:

err=Error from server (Forbidden): User "system:serviceaccount:myproject:sa" cannot create buildconfigs in project "null", verb=create, cmd=oc --server=https://mycluster --insecure-skip-tls-verify --namespace=null --token=XXXXX create -f /tmp/create4591596161239617922.markup -o=name , out=, status=1}

Rolling the client and sync plugins back to our previous versions 1.0.7 (client) and 1.0.3 (sync) makes the .create(.process()) work again.

**Comment by gabemontero** [comment]
hey @diamark 

Yep, v1.0.8 took a big leap in a addressing lists with multiple projects, re: the issue you noted, and we are picking up some loose ends in the aftermath.  `openshift.create` had a large portion of the change there (whereas openshift.process did not need any given how the template processing on the openshift side handles multinamespace issues for us).

Is there anyway you can provide a `toString()` on the `ArrayList<HashMap>` that is produced by your `openshift.process` call?  And if there sensitive data, perhaps obfuscate those strings, etc.

We need to right permatation of api objects and namespaces you have to run through our new algorithm and sort out the issue.

thanks

**Comment by mdraheim** [comment]
@gabemontero thanks for the explanation. I will provide the info over the weekend. Reading #96 again, would setting namespace to each object by means of template parameter be a workaround? The objects all go to the same namespace and the templates do not have namespace fields. But I can see the benefit of having lists of objects with different namespaces.

**Comment by gabemontero** [comment]
hey @mdraheim - wrt setting the namespace explicitly on each object, if you have not tried it already, yes, it could be a viable workaround.

Can't say for certainty of course without understanding the root cause.  The code as it is today does attempt to determine if all the objects are in the same namespace and react accordingly.  If you object list does in fact meet that pattern, then seeing your list of objects vs. the sample ones we test with would be of great benefit in determining the root cause.

I'll await word on any results you have, as well as that sample data that we can test against.

thanks

**Comment by gabemontero** [comment]
The output/template from @diamark was helpful

I believe the issue stems from the fact that the template has a single api obj, and not a list, and the new changes in the plugin to support multi-namespace do not handle that scenario correctly.  In revisiting our testcases, the template process/create flows deal only with templates which have lists of api objects.

Specifically:

```
apiVersion: v1
kind: Template
metadata:
  name: petclinic-${STACK}-${BRANCH}
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: petclinic-${STACK}-${BRANCH}
      application: petclinic
      template: build-${STACK}-${BRANCH}
      xpaas: 1.3.2
      branch: ${BRANCH}
      commit: ${REV}
    name: petclinic-${STACK}-${BRANCH}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: petclinic:${BRANCH}
    postCommit: {}
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 1Gi
    runPolicy: Serial
    source:
      binary:
        asFile: petclinic.war
      dockerfile: |-
        FROM jboss-webserver30-tomcat8-openshift:latest
        COPY petclinic.war /opt/webserver/webapps/petclinic.war
      type: Binary
    strategy:
      dockerStrategy:
        env:
        - name: REV
          value: ${REV}
        - name: BRANCH
          value: ${BRANCH}
        from:
          kind: ImageStreamTag
          name: jboss-webserver30-tomcat8-openshift:latest
          namespace: openshift
      type: Docker
parameters:
  - name: REV
    description: "The git revision the build is based on"
    value: "unspecified"
  - name: BRANCH
    description: "The git branch the build is based on"
    value: "unspecified"
  - name: STACK
    description: "The stack which created objects belong to"
    value: "unspecified"
  - name: COLOR
    description: "Color label of the prod deployment, empty in most cases"
    value: ""
  - name: CATALINA_OPTS
    description: "Generated opts to help name resolution"
    value: ""

```

I do not think whether the namespace is specified or not matters, as we do not specify the namespace in our existing tests.   But i'll use the form of the above in constructing a new test case and confirm.
