### ISSUE TITLE
exported selectors are missing quotations on some fields

### ISSUE THREAD

**Issue by tomcooperca** [openshift/jenkins-client-plugin#153]
oc version
oc v3.6.1+008f2d5
kubernetes v1.6.1+5115d708d7

Client plugin version 1.07

Not sure if this is a client plugin bug or just the CLI version I'm using.
We have a pipeline script that backs up all our OpenShift resources. 
When trying to recreate any of these objects (using an `DeploymentConfig` as an example) from the backup, a number of fields are not quoted and thus are being interpreted as the wrong datatype via the CLI (numbers or booleans, expecting only plain strings).

When I export this dc via `oc get dc my-dc -o yaml --export`, those field values are surrounded correctly. 

Pipeline:
```Groovy
openshift.selector('dc').withEach {
    sh "echo \"${it.asYaml(exportable: true)}\" > ${it.object().metadata.name}.yml"
}
```

Result:

```
apiVersion: v1
kind: DeploymentConfig
..
spec:
  template:
    spec:
      containers:
      - env:
        ...
        - name: SOME_NUMBER_VALUE
          value: 0
        - name: AB_JOLOKIA_OFF
          value: true
```

Recreating:

```
cat my-dc.yml | oc --loglevel=8 create -f -
I0426 14:44:52.523698   55118 request.go:991] Request Body: {"apiVersion":"v1","kind":"DeploymentConfig","metadata":..{"name":"SOME_NUMBER_VALUE","value":0},{"name":"AB_JOLOKIA_OFF","value":true}],
...
I0426 14:44:52.679359   55118 request.go:991] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"DeploymentConfig in version \"v1\" cannot be handled as a DeploymentConfig: [pos 758]: json: expect char '\"' but got char '0'","reason":"BadRequest","code":400}
```

Environment variables in dc's can only be strings so these values are being rejected. Exporting the resource manually gives me quoted values in those fields:

```
oc get pvc my-dc -n my-namespace -o yaml --export > my-dc.yml

diff --git a/my-namespace/dc/my-dc.yml b/my-namespace/dc/my-dc.yml
index 6e50285..a33d89f 100644
--- a/my-namespace/dc/my-dc.yml
+++ b/my-namespace/dc/my-dc.yml
@@ -7,6 +7,7 @@ metadata:
     app: my-dc
     template: template-deploy
   name: my-dc
+  selfLink: /oapi/v1/namespaces//deploymentconfigs/my-dc
 spec:
   replicas: 1
   selector:
@@ -35,9 +36,9 @@ spec:
         - name: EUREKA_INSTANCE_HOSTNAME
           value: my-dc
         - name: SOME_NUMBER_VALUE
-          value: 0
+          value: "0"
         - name: AB_JOLOKIA_OFF
-          value: true
+          value: "true"
         image: ...
```

**Comment by gabemontero** [comment]
I'm inclined to say it is an `oc` issue, assuming you've used the jenkins global config tool to import the 3.6 `oc` binary into your jenkins, and have manually installed this plugin in there.  If you are doing this out of the openshift jenkins image, if you are at 1.0.7 of the plugin, you have a much later `oc`, and that is the first thing you need to address ... get the 3.6 oc into jenkins.

But, if it is 3.6 oc in jenkins, and we've hit some sort of cli issue ...

... I will say that the `exportable: true` results in a call to `oc export ...`, not `oc get --export`.

I *would think* those should result in the same output, but either a) if they don't, and that is either the bug, or the unfortunate "feature" in this case, or b) to do what you want, you need to do an `oc get ... --export` instead, which for this plugin, would entail using the `raw` command.

Or this is a problem in how this yaml bubbles up to groovy and back

I would suggest the following debug steps:
1) try running `oc export ...` instead of `c get pvc my-pvc -o yaml --export` from the command line, see what those annotations look like
2) split out the `${it.asYaml(exportable: true)}` piece and see if those annotations look right before it is sent to the file
3) run `openshift.loglevel(10)` before calling `asYaml`, see what that annotation looks like in the raw REST flows

**Comment by tomcooperca** [comment]
Thanks @gabemontero - I also updated the original issue with a more practical example (a DeploymentConfig). Straight away, I'm see the same outputs from `oc export` (yay!) so those quotations are _supposed_ to be present. 

I'll get the `oc` binary with matched versions and the additional debug logs from the pipeline job.

**Comment by tomcooperca** [comment]
D'oh - this is a stupid Groovy problem within the pipeline script. Using the output of the selector instead a `sh` block is stripping off the quotes.

closing, not an issue with the plugin. Below logs (didn't even need debug logs to see this...) validate the expected behavior.

```
[Pipeline] _OcAction
[Pipeline] echo
apiVersion: v1
kind: DeploymentConfig
...
spec:
  template:
    spec:
      containers:
      - env:
        - name: SOME_NUMBER_VALUE
          value: "0"
        - name: AB_JOLOKIA_OFF
          value: "true"
 ...
[Pipeline] sh
[pipeline_testing] Running shell script
+ echo 'apiVersion: v1
kind: DeploymentConfig
metadata:
spec:
  template:
    spec:
      containers:
      - env:
        - name: SOME_NUMBER_VALUE
          value: 0
        - name: AB_JOLOKIA_OFF
          value: true
```

```Groovy
def dcSelectors = openshift.selector('dc', 'my-dc').withEach {
    echo it.asYaml(exportable: true)
    sh "echo \"${it.asYaml(exportable: true)}\""
}
```
