### ISSUE TITLE
openshift.process fails converting stdOut to Json

### ISSUE THREAD

**Issue by toschder** [openshift/jenkins-client-plugin#271]
I´m trying to `openshift.process(.....)` my template, to than `openshift.apply(....)` it.

When invoking
```
def configYaml = script.readYaml file: deploymentConfigFile
def openshift = script.openshift

openshift.logLevel(3)
openshift.withCluster(clusterName) {
	openshift.withProject(project) {
		if (configYaml.kind == "Template") {
			def list = openshift.process(configYaml, "-p", "PROJECT=${project}")
...
```

I sometimes get this message:

`Verbose sub-step output:
	Command> oc --server=https://myserver --insecure-skip-tls-verify --namespace=myproject --loglevel=3 --token=XXXXX process -f /home/jenkins/workspace/myJenkinsProject/DeployTo-DEV3.9/process2542071550542573450.markup -p PROJECT=myproject -o=json 
	Status> 0
 	StdOut>I0527 13:09:35.632846      27 cached_discovery.go:77] skipped caching discovery info due to the server could not find the requested resource
 I0527 13:09:35.644406      27 cached_discovery.go:77] skipped caching discovery info due to the server could not find the requested resource
I0527 13:09:35.651263      27 cached_discovery.go:77] skipped caching discovery info due to the server could not find the requested resource
I0527 13:09:35.654638      27 cached_discovery.go:77] skipped caching discovery info due to the server could not find the requested resource
 {
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "apiVersion": "v1",
            "kind": "DeploymentConfig",
            "metadata": {`
It looks like the response from the server isn´t properly parsed, resulting in 
```
Exception encountered: JsonException (Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'I' with an int value of 73
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  I0527 13:09:35.632846      27 cached_discovery.go:77] skipped caching discovery info due to the server could not find the requested resource
  ^)

```

How can this be fixed / workarounded ?

**Comment by toschder** [comment]
I removed the logLevel(3) - but than I cannot see the 
`oc --namespace --server......` commands anymore. These are required in the logs files for better traceability.

I would suggest changing the method and add a statement to "extract" the json part:
```
// OpenShiftDSL.groovy
public HashMap serializableMap(String json) {
    // remove trailing *.go output from the passed argument (if loglevel is set)
    String jsonStripped =json.drop(json.indexOf('{'))
    ....
}
```

**Comment by waveywaves** [comment]
Hello @toschder !
openshift.process is only meant to parse templates, if you pass in anything else, it should fail to read the contents of the file as the provided resource is not a template. I tested this out with `oc process` command for a given file with a Service defined and got the following error.

```
error: unable to parse "nodejsexheadless.yaml", not a valid Template but *v1.Service
```

When I tested openshift.process with the following in the Jenkins Pipeline
```
openshift.withCluster() {
                        def template = openshift.process(templatePath)
                        println(template.kind)
                        oc.apply(template)
                    }
```
it worked with the following output in the logs which notes down the `kind` of all the resources in the template and also creates all the resources in the templates.

```
[Secret, Service, Route, ImageStream, BuildConfig, DeploymentConfig, PersistentVolumeClaim, Service, DeploymentConfig]
```
You won't be able to `openshift.process` any other resource apart from Templates sucessfully as it is not supported by openshift.process.

**Comment by toschder** [comment]
hello @waveywaves I´m passing a valid template.yaml to openshift.process(.....) , see my code sample:

```
def configYaml = script.readYaml file: deploymentConfigFile
def openshift = script.openshift

openshift.logLevel(3)
openshift.withCluster(clusterName) {
	openshift.withProject(project) {
		if (configYaml.kind == "Template") {
			def list = openshift.process(configYaml, "-p", "PROJECT=${project}")
...
```

**BUT**: If you enable the **_logLevel(3)_** the openshift.process(....) call will internally first get back a String starting with some *.go output 

`StdOut>I0527 13:09:35.632846 27 cached_discovery.go:77] skipped caching discovery info due to the server could not find the requested resource I0527 13:09:35.644406 27 cached_discovery.go:77] skipped caching discovery info due to the server could not find the requested resource I0527 13:09:35.651263 27 cached_discovery.go:77] skipped caching discovery info due to the server could not find the requested resource I0527 13:09:35.654638 27 cached_discovery.go:77] skipped caching discovery info due to the server could not find the requested resource ..........
`

.... and after that *.go debug statements the interesting *.json output:

`.....{ "kind": "List", "apiVersion": "v1", "metadata": {}, "items": [ { "apiVersion": "v1", "kind": "DeploymentConfig", "metadata": {
`
This whole (debug statements + json) r.out String will than be passed to serializableMap(String json) - with the assumption that it´s plain json - but it is NOT !
```
    public ArrayList<HashMap> process(Object obj,Object... oargs) throws AbortException {
	    ...
		
        // Output should be JSON; unmarshall into a map and transform into a list of objects.
        return unwrapOpenShiftList(serializableMap(r.out));
    }

```
=> the serializableMap(String out ) should apply a RegEx like ^.*(\{.*\})$ or the mentioned drop(....) first, to extract the *.json from the given output.

**Comment by gabemontero** [comment]
@toschder @waveywaves we need the contents of the `configYaml` to debug

We've got test cases in our regression bucket that look like @toschder 's example usage of `openshift.process` but the contents of the yaml are the key.  More pain wrt groovy string parsing.  There has been pain with this in the past.

Also @toschder just as a sanity check, clarify the plugin version just so we know we are talking the same level (though I suspect you are at near the latest if I recall prior interactions).

**Comment by toschder** [comment]
Hi @gabemontero sorry for missing the version number, but it´s just the latest version.
To be able to reproduce the issue you can try with any Template, but you need to set the logLevel(..) -and you have to make sure that the CLI will complain with a message (which may depend on the current state of your openshift cluster, for example if the image was deployed before or whatever)
In my example I mentioned the output `skipped caching discovery info due to the server could not find the requested resource` from the CLI, before the *.json parts.
The Result.out (r.out) will contain the **whole** output of the underlying API call(s) - and **NOT** only the *.json structure! Whenever you want to convert this into a Map, you have to _strip of any lines that are NOT *.json_.
Anyway, here´s my DeploymentConfig (replace ${project.version} with a valid string.
```
---
kind: Template
apiVersion: v1
metadata:
  name: ms-azure-rawdata-extract-deployment
  annotations:
    description: Create ms-azure-rawdata-extract-deployment deployment on Openshift.
    tags: ms-azure-rawdata-extract-deployment
labels:
  template: ms-azure-rawdata-extract-deployment
  group: ms-azure-rawdata-extract-deployment
message: ms-azure-rawdata-extract-deployment deployment on Openshift

objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: iqpress-ol-ms-azure-rawdata-extract
      description: "iqpress-ol-ms-azure-rawdata-extract"
    name: ms-azure-rawdata-extract-deployment
  spec:
    replicas: 1
    selector:
      deploymentconfig: ms-azure-rawdata-extract-deployment
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8081"
          prometheus.io/scheme: https
          prometheus.io/scrape: "true"
        labels:
          app: iqpress-ol-ms-azure-rawdata-extract
          description: "RawData-Extraction"
          deploymentconfig: ms-azure-rawdata-extract-deployment
      spec:
        containers:
        - name: iqpress-ol-ms-azure-rawdata-extract
          # TODO need to qualify the internal registry here ?
          image: docker-registry.default.svc:5000/${PROJECT}}/iqpress-ol-ms-azure-rawdata-extract:${project.version}
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "confluent-kafka-service:9092"
            - name: KAFKA_TOPIC_INGRESS
              value: "RawData"
            - name: KAFKA_TOPIC_EGRESS
              value: "RawDataExtracted"
            - name: KAFKA_ERROR_TOPIC_EGRESS
              value: "RawDataExtractedErrors"
            - name: KAFKA_GROUP_ID
              value: "IQPressRawDataConsumerGroup"          
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTPS
            initialDelaySeconds: 300
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 15
          ports:
          - containerPort: 8000
            name: jolokia
            protocol: TCP
          - containerPort: 8081
            name: https
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
    triggers: []
parameters:
  - name: PROJECT
    description: "project need to be set if different from default 'iqpress'"
    value: "iqpress"  
```
