### ISSUE TITLE
patch value 

### ISSUE THREAD

**Issue by DRAKUN** [openshift/jenkins-client-plugin#301]
hello i can't patch value 
```sh
java.lang.NullPointerException: Cannot set property 'name' on null object
```

my code is 
```groovy
...
def secretname = "dev-stack"
def select_obj = openshift.selector( 'ingresscontroller/api' )
if (select_obj.exists()) {
    // si l'ingress controller existe donc rien a faire
    def objs = select_obj.object()
    println "L'ingressController << - API - >> existe deja"
     // PATCHING CERTIFICAT
     objs.spec.defaultCertificate['name'] = secretname
     openshift.apply(objs)
 }
...
```

In commande line il try todo this 

```sh
oc patch ingresscontroller.operator api--type=merge -p '{"spec":{"defaultCertificate": {"name": "dev-stack"}}}' -n openshift-ingress-operator
```
Natively defaultCertificate doesn't existe

```yaml
spec:
  domain: api.dev.stack.com
  namespaceSelector:
    matchLabels:
      type: api-apps
  replicas: 2
```

Someone can help me
